/**
 * CharacterSave — C1 persistent character storage.
 *
 * All data is stored in localStorage.  All methods are static.
 *
 * localStorage keys:
 *   arpg_char_index          — JSON array of CharacterSummary objects (fast list view)
 *   arpg_char_<id>           — full JSON character data blob
 */

const NAMESPACE  = 'arpg_char_';
const INDEX_KEY  = 'arpg_char_index';

// ── Internal index helpers ────────────────────────────────────────────────────

function getIndex() {
  try {
    const raw = localStorage.getItem(INDEX_KEY);
    return raw ? JSON.parse(raw) : [];
  } catch { return []; }
}

function setIndex(index) {
  try { localStorage.setItem(INDEX_KEY, JSON.stringify(index)); } catch {}
}

// ── Public API ────────────────────────────────────────────────────────────────

export class CharacterSave {
  /**
   * Persist a full character data object.
   * Also updates the lightweight index entry used by list().
   * @param {string} characterId
   * @param {object} data  — full character data (matches schema below)
   */
  static save(characterId, data) {
    try {
      const now = new Date().toISOString();
      const blob = JSON.stringify({ ...data, lastPlayed: now });
      localStorage.setItem(NAMESPACE + characterId, blob);

      // Upsert index entry
      const index = getIndex();
      const idx   = index.findIndex((e) => e.id === characterId);
      const summary = {
        id:         characterId,
        name:       data.name       ?? 'Exile',
        class:      data.class      ?? 'sage',
        level:      data.level      ?? 1,
        created:    data.created    ?? now,
        lastPlayed: now,
      };
      if (idx >= 0) index[idx] = summary;
      else          index.push(summary);
      setIndex(index);
    } catch (e) {
      console.error('[CharacterSave] save failed:', e);
    }
  }

  /**
   * Load a full character data object.
   * @param {string} characterId
   * @returns {object|null}
   */
  static load(characterId) {
    try {
      const raw = localStorage.getItem(NAMESPACE + characterId);
      return raw ? JSON.parse(raw) : null;
    } catch { return null; }
  }

  /**
   * Return lightweight summaries of all saved characters,
   * sorted by lastPlayed descending (most recent first).
   * @returns {Array<{ id, name, class, level, created, lastPlayed }>}
   */
  static list() {
    const index = getIndex();
    return [...index].sort(
      (a, b) => new Date(b.lastPlayed ?? 0) - new Date(a.lastPlayed ?? 0),
    );
  }

  /**
   * Delete a character and remove it from the index.
   * @param {string} characterId
   */
  static delete(characterId) {
    try {
      localStorage.removeItem(NAMESPACE + characterId);
      setIndex(getIndex().filter((e) => e.id !== characterId));
    } catch {}
  }

  /**
   * True if a character with this id exists in localStorage.
   * @param {string} characterId
   * @returns {boolean}
   */
  static exists(characterId) {
    try { return localStorage.getItem(NAMESPACE + characterId) !== null; }
    catch { return false; }
  }

  /**
   * Build the initial save data for a brand-new character.
   *
   * @param {string} id         — crypto.randomUUID() generated by caller
   * @param {string} name       — player-entered name
   * @param {import('./data/characters.js').CharacterDef} charDef — from CHARACTERS
   * @returns {object}          — full character data blob
   */
  static createInitial(id, name, charDef) {
    const now = new Date().toISOString();
    return {
      id,
      name,
      class:      charDef.id,
      created:    now,
      lastPlayed: now,

      // ── Combat stats ──────────────────────────────────────────────────────
      level:          1,
      xp:             0,
      health:         charDef.baseStats?.maxHealth ?? 100,
      maxHealth:      charDef.baseStats?.maxHealth ?? 100,
      mana:           charDef.baseStats?.maxMana ?? 100,
      maxMana:        charDef.baseStats?.maxMana ?? 100,
      energyShield:   0,
      maxEnergyShield: 0,
      gold: 0,

      // ── Systems ───────────────────────────────────────────────────────────
      // passiveTree.allocated mirrors the pre-allocated tree start nodes.
      passiveTree: {
        allocated: Array.isArray(charDef.treeStartNodes)
          ? [...charDef.treeStartNodes, 'start']
          : ['start'],
      },
      metaTree:    { allocated: [] },

      // Inventory is empty; grid matches InventoryGrid default (12×6).
      inventory: { cols: 12, rows: 6, items: [] },

      // All equipment slots vacant.
      equipment: {
        mainhand:  null, offhand:   null,
        bodyarmor: null, helmet:    null,
        boots:     null, belt:      null,
        ring1:     null, ring2:     null,
        amulet:    null, gloves:    null,
      },

      // Three active skill slots — empty to start.
      activeSkills: [null, null, null],

      // Starter auto-fire weapon from the character definition.
      autoSkills: [charDef.startingWeapon ?? 'MAGIC_BOLT'],

      // ── Map progress ──────────────────────────────────────────────────────
      actsCleared: [],
      actsClearedAt: {},
      mapsCleared: 0,
      bossesKilled: [],

      // Per-character meta currency (account-wide stash is separate).
      chaosShards: 0,
    };
  }
}
