import { ArcaneLance } from '../../skills/ArcaneLance.js';
import { MagicBolt } from '../../skills/MagicBolt.js';
import { FrostArrow } from '../../skills/FrostArrow.js';
import { FireStrike } from '../../skills/FireStrike.js';
import { PhantomBlade } from '../../skills/PhantomBlade.js';
import { TectonicCleave } from '../../skills/TectonicCleave.js';
import { BoneSpear } from '../../skills/BoneSpear.js';
import { ChainLightning } from '../../skills/ChainLightning.js';
import { VoidShardSwarm } from '../../skills/VoidShardSwarm.js';
import {
  PiercingShot,
  SplitShot,
  FrostVolley,
  ThunderVolley,
  EmberArrow,
  GaleShot,
  SeekerArrow,
  Barrage,
  StarfallArrow,
} from '../../skills/BowSkillPack.js';
import {
  ChaosBlink,
  FrostNova,
  GravityWell,
  BloodPact,
  WraithSummon,
  TimeWarp,
  IronBulwark,
  ArcaneSurge,
  Fireball,
  GlacialCascade,
  LightningStrike,
  BladeFlurry,
  Earthquake,
  Vortex,
} from './skillClasses.js';

export const SKILL_OFFER_POOL = [
  {
    id: 'MAGIC_BOLT',
    name: 'Magic Bolt',
    description: 'Fire a basic magical bolt at your target.',
    isActiveSkill: true,
    available: (player) => !player.autoSkills.some((w) => w.id === 'MAGIC_BOLT'),
    create: () => new MagicBolt(),
  },
  {
    id: 'FROST_ARROW',
    name: 'Frost Arrow',
    description: 'Fires a chilling arrow that can slow enemies.',
    isActiveSkill: true,
    available: (player) => !player.autoSkills.some((w) => w.id === 'FROST_ARROW'),
    create: () => new FrostArrow(),
  },
  {
    id: 'FIRE_STRIKE',
    name: 'Fire Strike',
    description: 'A searing melee strike that applies blaze damage.',
    isActiveSkill: true,
    available: (player) => !player.autoSkills.some((w) => w.id === 'FIRE_STRIKE'),
    create: () => new FireStrike(),
  },
  {
    id: 'PIERCING_SHOT',
    name: 'Piercing Shot',
    description: 'Fires a piercing bow shot that cuts through enemies.',
    isActiveSkill: true,
    available: (player) => !player.autoSkills.some((w) => w.id === 'PIERCING_SHOT'),
    create: () => new PiercingShot(),
  },
  {
    id: 'SPLIT_SHOT',
    name: 'Split Shot',
    description: 'Fires a fan of arrows for broad coverage.',
    isActiveSkill: true,
    available: (player) => !player.autoSkills.some((w) => w.id === 'SPLIT_SHOT'),
    create: () => new SplitShot(),
  },
  {
    id: 'FROST_VOLLEY',
    name: 'Frost Volley',
    description: 'Rapid frost-tipped bow shots that chill enemies.',
    isActiveSkill: true,
    available: (player) => !player.autoSkills.some((w) => w.id === 'FROST_VOLLEY'),
    create: () => new FrostVolley(),
  },
  {
    id: 'THUNDER_VOLLEY',
    name: 'Thunder Volley',
    description: 'Electrified bow arrows strike in a tight burst.',
    isActiveSkill: true,
    available: (player) => !player.autoSkills.some((w) => w.id === 'THUNDER_VOLLEY'),
    create: () => new ThunderVolley(),
  },
  {
    id: 'EMBER_ARROW',
    name: 'Ember Arrow',
    description: 'A blazing bow arrow with light blaze damage.',
    isActiveSkill: true,
    available: (player) => !player.autoSkills.some((w) => w.id === 'EMBER_ARROW'),
    create: () => new EmberArrow(),
  },
  {
    id: 'GALE_SHOT',
    name: 'Gale Shot',
    description: 'A high-speed bow shot with rapid cadence.',
    isActiveSkill: true,
    available: (player) => !player.autoSkills.some((w) => w.id === 'GALE_SHOT'),
    create: () => new GaleShot(),
  },
  {
    id: 'SEEKER_ARROW',
    name: 'Seeker Arrow',
    description: 'A focused bow shot tuned for heavy single-target hits.',
    isActiveSkill: true,
    available: (player) => !player.autoSkills.some((w) => w.id === 'SEEKER_ARROW'),
    create: () => new SeekerArrow(),
  },
  {
    id: 'BARRAGE',
    name: 'Barrage',
    description: 'Rapid narrow spread of bow arrows.',
    isActiveSkill: true,
    available: (player) => !player.autoSkills.some((w) => w.id === 'BARRAGE'),
    create: () => new Barrage(),
  },
  {
    id: 'STARFALL_ARROW',
    name: 'Starfall Arrow',
    description: 'Sacred bow arrow blending physical and holy damage.',
    isActiveSkill: true,
    available: (player) => !player.autoSkills.some((w) => w.id === 'STARFALL_ARROW'),
    create: () => new StarfallArrow(),
  },
  {
    id: 'PHANTOM_BLADE',
    name: 'Phantom Blade',
    description: 'Hurl a spectral blade in your facing direction.',
    isActiveSkill: true,
    available: (player) => !player.autoSkills.some((w) => w.id === 'PHANTOM_BLADE'),
    create: () => new PhantomBlade(),
  },
  {
    id: 'TECTONIC_CLEAVE',
    name: 'Tectonic Cleave',
    description: 'Launch a massive earth-rending projectile that pierces all enemies.',
    isActiveSkill: true,
    available: (player) => !player.autoSkills.some((w) => w.id === 'TECTONIC_CLEAVE'),
    create: () => new TectonicCleave(),
  },
  {
    id: 'BONE_SPEAR',
    name: 'Bone Spear',
    description: 'Impale enemies with a slow, devastating piercing bone shard.',
    isActiveSkill: true,
    available: (player) => !player.autoSkills.some((w) => w.id === 'BONE_SPEAR'),
    create: () => new BoneSpear(),
  },
  {
    id: 'CHAIN_LIGHTNING',
    name: 'Chain Lightning',
    description: 'Discharge a bolt that arcs to up to 4 additional nearby enemies.',
    isActiveSkill: true,
    available: (player) => !player.autoSkills.some((w) => w.id === 'CHAIN_LIGHTNING'),
    create: () => new ChainLightning(),
  },
  {
    id: 'VOID_SHARD_SWARM',
    name: 'Void Shard Swarm',
    description: 'Fire 3 spiraling shards that home in on the nearest enemy.',
    isActiveSkill: true,
    available: (player) => !player.autoSkills.some((w) => w.id === 'VOID_SHARD_SWARM'),
    create: () => new VoidShardSwarm(),
  },
  {
    id: 'ARCANE_LANCE',
    name: 'Arcane Lance',
    description: 'Fire a precise magical bolt at the nearest enemy.',
    isActiveSkill: true,
    available: (player) => !player.autoSkills.some((w) => w.id === 'ARCANE_LANCE'),
    create: () => new ArcaneLance(),
  },
  {
    id: 'blink',
    name: 'Chaos Blink',
    description: 'Teleport 200 px forward and gain brief invulnerability.',
    isActiveSkill: false,
    available: (_player, engine) => !engine.activeSkillSystem.hasPureSkill('blink'),
    createSkill: () => new ChaosBlink(),
  },
  {
    id: 'frost_nova',
    name: 'Frost Nova',
    description: 'Freeze all enemies within 250 px for 2 s and deal 15 damage.',
    isActiveSkill: false,
    available: (_player, engine) => !engine.activeSkillSystem.hasPureSkill('frost_nova'),
    createSkill: () => new FrostNova(),
  },
  {
    id: 'gravity_well',
    name: 'Gravity Well',
    description: 'Pull all enemies within 350 px violently toward you.',
    isActiveSkill: false,
    available: (_player, engine) => !engine.activeSkillSystem.hasPureSkill('gravity_well'),
    createSkill: () => new GravityWell(),
  },
  {
    id: 'blood_pact',
    name: 'Blood Pact',
    description: 'Sacrifice 25% HP for +80% damage for 4 s.',
    isActiveSkill: false,
    available: (_player, engine) => !engine.activeSkillSystem.hasPureSkill('blood_pact'),
    createSkill: () => new BloodPact(),
  },
  {
    id: 'wraith_summon',
    name: 'Summon Wraith',
    description: 'Send a wraith to the nearest enemy; it explodes on arrival for 200 damage.',
    isActiveSkill: false,
    available: (_player, engine) => !engine.activeSkillSystem.hasPureSkill('wraith_summon'),
    createSkill: () => new WraithSummon(),
  },
  {
    id: 'time_warp',
    name: 'Time Warp',
    description: 'Slow all enemies to 20% speed for 3 s.',
    isActiveSkill: false,
    available: (_player, engine) => !engine.activeSkillSystem.hasPureSkill('time_warp'),
    createSkill: () => new TimeWarp(),
  },
  {
    id: 'bulwark',
    name: 'Iron Bulwark',
    description: 'Erect a shield that absorbs the next 80 damage for 3 s.',
    isActiveSkill: false,
    available: (_player, engine) => !engine.activeSkillSystem.hasPureSkill('bulwark'),
    createSkill: () => new IronBulwark(),
  },
  {
    id: 'arcane_surge',
    name: 'Arcane Surge',
    description: 'Reset all cooldowns and fire weapons at near-zero cost for 2 s. +30% cast speed for 6 s.',
    isActiveSkill: false,
    available: (_player, engine) => !engine.activeSkillSystem.hasPureSkill('arcane_surge'),
    createSkill: () => new ArcaneSurge(),
  },
  {
    id: 'fireball',
    name: 'Fireball',
    description: 'Arcing fireball detonates in 60 px AoE on impact; ignites enemies.',
    isActiveSkill: false,
    available: (_player, engine) => !engine.activeSkillSystem.hasPureSkill('fireball'),
    createSkill: () => new Fireball(),
  },
  {
    id: 'glacial_cascade',
    name: 'Glacial Cascade',
    description: '5 ice pillars along a line; each damages and chills enemies.',
    isActiveSkill: false,
    available: (_player, engine) => !engine.activeSkillSystem.hasPureSkill('glacial_cascade'),
    createSkill: () => new GlacialCascade(),
  },
  {
    id: 'lightning_strike',
    name: 'Lightning Strike',
    description: 'Melee burst + 3 lightning bolts forward; applies Shock.',
    isActiveSkill: false,
    available: (_player, engine) => !engine.activeSkillSystem.hasPureSkill('lightning_strike'),
    createSkill: () => new LightningStrike(),
  },
  {
    id: 'blade_flurry',
    name: 'Blade Flurry',
    description: 'Build up to 6 stages then unleash a scaling melee AoE burst.',
    isActiveSkill: false,
    available: (_player, engine) => !engine.activeSkillSystem.hasPureSkill('blade_flurry'),
    createSkill: () => new BladeFlurry(),
  },
  {
    id: 'earthquake',
    name: 'Earthquake',
    description: 'Instant ground slam + aftershock 1.5 s later at origin.',
    isActiveSkill: false,
    available: (_player, engine) => !engine.activeSkillSystem.hasPureSkill('earthquake'),
    createSkill: () => new Earthquake(),
  },
  {
    id: 'vortex',
    name: 'Vortex',
    description: 'Chilling cold vortex at target; pulses damage/tick for 3 s; applies Chill.',
    isActiveSkill: false,
    available: (_player, engine) => !engine.activeSkillSystem.hasPureSkill('vortex'),
    createSkill: () => new Vortex(),
  },
];
