export const MIGRATED_MAP_DEFINITIONS = [
  {
    id: 'act1_part1_fallen_cloister',
    name: 'Act I - Part I: The Fallen Cloister',
    tier: 1,
    campaignPart: 1,
    description: 'Shattered halls and corrupted acolytes.',
    unlockReq: null,
    biomePackId: 'pack_ruined_keep',
    layoutProfileId: 'layout_ruins_linear',
    encounterProfileId: 'encounter_act1_cloister',
    rewardProfileId: 'reward_act1_basic',
  },
  {
    id: 'act1_part2_ashen_approach',
    name: 'Act I - Part II: Ashen Approach',
    tier: 1,
    campaignPart: 2,
    description: 'Ash drifts across ruined entryways and barracks.',
    unlockReq: 'act1_part1_fallen_cloister',
    biomePackId: 'pack_ruined_keep',
    layoutProfileId: 'layout_ruins_linear',
    encounterProfileId: 'encounter_act1_cloister',
    rewardProfileId: 'reward_act1_basic',
  },
  {
    id: 'act1_part3_broken_courtyard',
    name: 'Act I - Part III: Broken Courtyard',
    tier: 1,
    campaignPart: 3,
    description: 'Collapsed cloisters open into exposed kill zones.',
    unlockReq: 'act1_part2_ashen_approach',
    biomePackId: 'pack_ruined_keep',
    layoutProfileId: 'layout_ruins_linear',
    encounterProfileId: 'encounter_act1_cloister',
    rewardProfileId: 'reward_act1_basic',
  },
  {
    id: 'act1_part4_cloister_sanctum',
    name: 'Act I - Part IV: Cloister Sanctum',
    tier: 1,
    campaignPart: 4,
    description: 'The inner sanctum where Act I resistance hardens.',
    unlockReq: 'act1_part3_broken_courtyard',
    biomePackId: 'pack_ruined_keep',
    layoutProfileId: 'layout_ruins_linear',
    encounterProfileId: 'encounter_act1_cloister',
    rewardProfileId: 'reward_act1_basic',
  },
  {
    id: 'act2_part1_scorched_foothills',
    name: 'Act II - Part I: Scorched Foothills',
    tier: 2,
    campaignPart: 1,
    description: 'Ash storms sweep through abandoned war camps.',
    unlockReq: 'act1_part4_cloister_sanctum',
    biomePackId: 'pack_siege_road',
    layoutProfileId: 'layout_wastes_open',
    encounterProfileId: 'encounter_act2_foothills',
    rewardProfileId: 'reward_act2_basic',
  },
  {
    id: 'act2_part2_siege_lines',
    name: 'Act II - Part II: Siege Lines',
    tier: 2,
    campaignPart: 2,
    description: 'Fortified chokepoints funnel combat into deadly lanes.',
    unlockReq: 'act2_part1_scorched_foothills',
    biomePackId: 'pack_siege_road',
    layoutProfileId: 'layout_wastes_open',
    encounterProfileId: 'encounter_act2_foothills',
    rewardProfileId: 'reward_act2_basic',
  },
  {
    id: 'act2_part3_war_torn_crossing',
    name: 'Act II - Part III: War-Torn Crossing',
    tier: 2,
    campaignPart: 3,
    description: 'Collapsed roads and embers hide relentless packs.',
    unlockReq: 'act2_part2_siege_lines',
    biomePackId: 'pack_siege_road',
    layoutProfileId: 'layout_wastes_open',
    encounterProfileId: 'encounter_act2_foothills',
    rewardProfileId: 'reward_act2_basic',
  },
  {
    id: 'act2_part4_blast_furnace_gate',
    name: 'Act II - Part IV: Blast Furnace Gate',
    tier: 2,
    campaignPart: 4,
    description: 'The final bastion before the flooded archives beyond.',
    unlockReq: 'act2_part3_war_torn_crossing',
    biomePackId: 'pack_siege_road',
    layoutProfileId: 'layout_wastes_open',
    encounterProfileId: 'encounter_act2_foothills',
    rewardProfileId: 'reward_act2_basic',
  },
  {
    id: 'act3_part1_sunken_archive',
    name: 'Act III - Part I: The Sunken Archive',
    tier: 3,
    campaignPart: 1,
    description: 'Flooded vaults guard forbidden arcana.',
    unlockReq: 'act2_part4_blast_furnace_gate',
    biomePackId: 'pack_fungal_grotto',
    layoutProfileId: 'layout_archive_flooded',
    encounterProfileId: 'encounter_act3_archive',
    rewardProfileId: 'reward_act3_basic',
  },
  {
    id: 'act3_part2_drowned_stacks',
    name: 'Act III - Part II: Drowned Stacks',
    tier: 3,
    campaignPart: 2,
    description: 'Toppled shelves and deep channels break line of sight.',
    unlockReq: 'act3_part1_sunken_archive',
    biomePackId: 'pack_fungal_grotto',
    layoutProfileId: 'layout_archive_flooded',
    encounterProfileId: 'encounter_act3_archive',
    rewardProfileId: 'reward_act3_basic',
  },
  {
    id: 'act3_part3_arcane_reservoir',
    name: 'Act III - Part III: Arcane Reservoir',
    tier: 3,
    campaignPart: 3,
    description: 'Ancient reservoirs pulse with hostile arcane pressure.',
    unlockReq: 'act3_part2_drowned_stacks',
    biomePackId: 'pack_fungal_grotto',
    layoutProfileId: 'layout_archive_flooded',
    encounterProfileId: 'encounter_act3_archive',
    rewardProfileId: 'reward_act3_basic',
  },
  {
    id: 'act3_part4_warden_annex',
    name: 'Act III - Part IV: Warden Annex',
    tier: 3,
    campaignPart: 4,
    description: 'A sealed annex where elites guard the cathedral route.',
    unlockReq: 'act3_part3_arcane_reservoir',
    biomePackId: 'pack_fungal_grotto',
    layoutProfileId: 'layout_archive_flooded',
    encounterProfileId: 'encounter_act3_archive',
    rewardProfileId: 'reward_act3_basic',
  },
  {
    id: 'act4_part1_blighted_cathedral',
    name: 'Act IV - Part I: Blighted Cathedral',
    tier: 4,
    campaignPart: 1,
    description: 'A desecrated sanctuary ruled by zealot champions.',
    unlockReq: 'act3_part4_warden_annex',
    biomePackId: 'pack_flooded_crypt',
    layoutProfileId: 'layout_cathedral_blighted',
    encounterProfileId: 'encounter_act4_cathedral',
    rewardProfileId: 'reward_act4_basic',
  },
  {
    id: 'act4_part2_pilgrim_transept',
    name: 'Act IV - Part II: Pilgrim Transept',
    tier: 4,
    campaignPart: 2,
    description: 'Narrow transepts force close fights against zealot packs.',
    unlockReq: 'act4_part1_blighted_cathedral',
    biomePackId: 'pack_flooded_crypt',
    layoutProfileId: 'layout_cathedral_blighted',
    encounterProfileId: 'encounter_act4_cathedral',
    rewardProfileId: 'reward_act4_basic',
  },
  {
    id: 'act4_part3_reliquary_depths',
    name: 'Act IV - Part III: Reliquary Depths',
    tier: 4,
    campaignPart: 3,
    description: 'Flooded reliquaries and bone halls tighten the gauntlet.',
    unlockReq: 'act4_part2_pilgrim_transept',
    biomePackId: 'pack_flooded_crypt',
    layoutProfileId: 'layout_cathedral_blighted',
    encounterProfileId: 'encounter_act4_cathedral',
    rewardProfileId: 'reward_act4_basic',
  },
  {
    id: 'act4_part4_sanctified_crypt',
    name: 'Act IV - Part IV: Sanctified Crypt',
    tier: 4,
    campaignPart: 4,
    description: 'The last cathedral trial before the embers ascent.',
    unlockReq: 'act4_part3_reliquary_depths',
    biomePackId: 'pack_flooded_crypt',
    layoutProfileId: 'layout_cathedral_blighted',
    encounterProfileId: 'encounter_act4_cathedral',
    rewardProfileId: 'reward_act4_basic',
  },
  {
    id: 'act5_part1_throne_of_embers',
    name: 'Act V - Part I: Throne of Embers',
    tier: 5,
    campaignPart: 1,
    description: 'The final ascent through a burning citadel.',
    unlockReq: 'act4_part4_sanctified_crypt',
    biomePackId: 'pack_spiral_abyss',
    layoutProfileId: 'layout_abyss_throne',
    encounterProfileId: 'encounter_act5_throne',
    rewardProfileId: 'reward_act5_basic',
  },
  {
    id: 'act5_part2_scorch_spiral',
    name: 'Act V - Part II: Scorch Spiral',
    tier: 5,
    campaignPart: 2,
    description: 'Spiral lanes and burning chokepoints punish mistakes.',
    unlockReq: 'act5_part1_throne_of_embers',
    biomePackId: 'pack_spiral_abyss',
    layoutProfileId: 'layout_abyss_throne',
    encounterProfileId: 'encounter_act5_throne',
    rewardProfileId: 'reward_act5_basic',
  },
  {
    id: 'act5_part3_cinder_bastion',
    name: 'Act V - Part III: Cinder Bastion',
    tier: 5,
    campaignPart: 3,
    description: 'Elite defenders hold the citadel amid volatile ruins.',
    unlockReq: 'act5_part2_scorch_spiral',
    biomePackId: 'pack_spiral_abyss',
    layoutProfileId: 'layout_abyss_throne',
    encounterProfileId: 'encounter_act5_throne',
    rewardProfileId: 'reward_act5_basic',
  },
  {
    id: 'act5_part4_ember_crown',
    name: 'Act V - Part IV: Ember Crown',
    tier: 5,
    campaignPart: 4,
    description: 'The final campaign proving ground before endgame maps.',
    unlockReq: 'act5_part3_cinder_bastion',
    biomePackId: 'pack_spiral_abyss',
    layoutProfileId: 'layout_abyss_throne',
    encounterProfileId: 'encounter_act5_throne',
    rewardProfileId: 'reward_act5_basic',
  },
];
