export const MIGRATED_MAP_DEFINITIONS = [
  {
    id: 'act1_fallen_cloister',
    name: 'Act I: The Fallen Cloister',
    tier: 1,
    description: 'Shattered halls and corrupted acolytes.',
    unlockReq: null,
    layoutProfileId: 'layout_ruins_linear',
    encounterProfileId: 'encounter_act1_cloister',
    rewardProfileId: 'reward_act1_basic',
  },
  {
    id: 'act2_scorched_foothills',
    name: 'Act II: Scorched Foothills',
    tier: 2,
    description: 'Ash storms sweep through abandoned war camps.',
    unlockReq: 'act1_fallen_cloister',
    layoutProfileId: 'layout_wastes_open',
    encounterProfileId: 'encounter_act2_foothills',
    rewardProfileId: 'reward_act2_basic',
  },
  {
    id: 'act3_sunken_archive',
    name: 'Act III: The Sunken Archive',
    tier: 3,
    description: 'Flooded vaults guard forbidden arcana.',
    unlockReq: 'act2_scorched_foothills',
    layoutProfileId: 'layout_archive_flooded',
    encounterProfileId: 'encounter_act3_archive',
    rewardProfileId: 'reward_act3_basic',
  },
  {
    id: 'act4_blighted_cathedral',
    name: 'Act IV: Blighted Cathedral',
    tier: 4,
    description: 'A desecrated sanctuary ruled by zealot champions.',
    unlockReq: 'act3_sunken_archive',
    layoutProfileId: 'layout_cathedral_blighted',
    encounterProfileId: 'encounter_act4_cathedral',
    rewardProfileId: 'reward_act4_basic',
  },
  {
    id: 'act5_throne_of_embers',
    name: 'Act V: Throne of Embers',
    tier: 5,
    description: 'The final ascent through a burning citadel.',
    unlockReq: 'act4_blighted_cathedral',
    layoutProfileId: 'layout_abyss_throne',
    encounterProfileId: 'encounter_act5_throne',
    rewardProfileId: 'reward_act5_basic',
  },
];
